source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

platform :ios, '7.0'
target :demo do

pod 'ATModuleManager', :podspec => 'https://github.com/linzhiman/ATModuleManager/blob/master/ATModuleManager.podspec?raw=1'

end

